
CREATE TABLE Client(
ID SERIAL NOT NULL,
PASSWORD TEXT NOT NULL,
EMAIL TEXT NOT NULL,
TELEPHONE TEXT NOT NULL,
NAME TEXT NOT NULL,
GENDER INT,
AGE INT,
PRIMARY KEY (ID)
);

CREATE TABLE BarberShop(
ID SERIAL NOT NULL,
PASSWORD TEXT NOT NULL,
EMAIL TEXT NOT NULL,
TELEPHONE TEXT NOT NULL,
NAME TEXT NOT NULL,
ADDRESS TEXT NOT NULL,
CITY TEXT NOT NULL,
PRIMARY KEY (ID)
); 

CREATE TABLE Review(
CLIENT_ID SERIAL NOT NULL REFERENCES Client(ID),
BARBER_SHOP_ID SERIAL NOT NULL REFERENCES BarberShop(ID),
DESCRIPTION TEXT NULL,
MARK REAL NOT NULL,
DATE DATE NOT NULL,
PRIMARY KEY (CLIENT_ID, BARBER_SHOP_ID)
);  

CREATE TABLE Service(
ID SERIAL NOT NULL,
BARBER_SHOP_ID SERIAL NOT NULL REFERENCES BarberShop(ID),
NAME TEXT NOT NULL,
PRICE REAL NOT NULL,
DURATION INT NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE Promotion(
ID SERIAL NOT NULL,
BARBER_SHOP_ID SERIAL NOT NULL REFERENCES BarberShop(ID),
SERVICE_ID SERIAL NOT NULL REFERENCES Service(ID),
NAME TEXT NOT NULL,
DESCRIPTION TEXT NOT NULL,
IS_PROMOTIONAL BOOLEAN NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE Appointment(
ID SERIAL NOT NULL,
CLIENT_ID SERIAL NOT NULL REFERENCES Client(ID),
BARBER_SHOP_ID SERIAL NOT NULL REFERENCES BarberShop(ID),
SERVICE_ID SERIAL NOT NULL REFERENCES Service(ID),
PROMOTION_ID SERIAL NOT NULL REFERENCES Promotion(ID),
DATE DATE NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE SpecialDay(
BARBER_SHOP_ID SERIAL NOT NULL REFERENCES BarberShop(ID),
DATE DATE NOT NULL,
TYPE INT NOT NULL,
PRIMARY KEY(BARBER_SHOP_ID, DATE)
);

CREATE TABLE Schedule(
BARBER_SHOP_ID SERIAL NOT NULL REFERENCES BarberShop(ID),
DAY_OF_WEEK INT NOT NULL,
OPENING_1 TEXT NOT NULL,
CLOSING_1 TEXT NOT NULL,
OPENING_2 TEXT NOT NULL,
CLOSING_2 TEXT NOT NULL,
APPOINTMENTS_AT_SAME_TIME INT NOT NULL,
PRIMARY KEY(BARBER_SHOP_ID, DAY_OF_WEEK)
);

CREATE TABLE DB_Version(
VERSION INT NOT NULL DEFAULT 0,
MODIFICATION_DATE DATE NOT NULL DEFAULT NOW()
);

DROP TABLE DB_VERSION;

